<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container42tJjE2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container42tJjE2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container42tJjE2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container42tJjE2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container42tJjE2\App_KernelDevDebugContainer([
    'container.build_hash' => '42tJjE2',
    'container.build_id' => '4c6814ce',
    'container.build_time' => 1685372184,
], __DIR__.\DIRECTORY_SEPARATOR.'Container42tJjE2');
